version: "2.4"

services:
  nginx:
    build: requirements/nginx/.
    image: nginx
    ports:
      - 443:443
    container_name: nginx
    networks:
      - Inception
    depends_on:
        - wordpress
    volumes:
      - WordPress_db:/var/www/html
    restart: "always"
  wordpress:
      env_file:
        - .env
      build: requirements/wordpress/.
      image: wordpress
      container_name: wordpress
      ports:
        - 9000:9000
      networks:
        - Inception
      depends_on:
        - mariadb
      volumes:
        - WordPress_db:/var/www/html
      restart: "always"
  mariadb:
      env_file:
        - .env
      build: requirements/mariadb/.
      image: mariadb
      container_name: mariadb
      ports:
        - 3306:3306
      networks:
        - Inception
      volumes:
        - DB:/var/lib/mysql/db_w
      restart: "always"
networks:
  Inception:
        name: Inception
volumes:
    WordPress_db:
     driver_opts:
          type: none
          device: /home/ssamadi/data/WordPress
          o: bind
    DB:
       driver_opts:
          type: none
          device: /home/ssamadi/data/DB
          o: bind