version: "2.4"
services:
  nginx:
    build: ./srcs/requirements/nginx/.
    image: nginx
    ports:
      - 443:443
    container_name: nginx
    networks:
      - Inception
    volumes:
      - /home/ssamadi/data/WordPress:/var/www/html
  wordpress:
      build: ./srcs/requirements/wordpress/.
      image: wordpress
      container_name: wordpress
      ports:
        - 9000:9000
      networks:
        - Inception
      depends_on:
        - mariadb
      volumes:
        - /home/ssamadi/data/WordPress:/var/www/html
  mariadb:
      build: ./srcs/requirements/mariadb/.
      image: mariadb
      container_name: mariadb
      ports:
        - 3306:3306
      networks:
        - Inception
      volumes:
        - /home/ssamadi/data/DB:/root/db
networks:
  Inception:
        name: Inception

