version: "2.4"
services:
  nginx:
    build: ./srcs/requirements/nginx/.
    image: nginx
    ports:
      - 443:443
    container_name: nginx
    networks:
      - Inception
    volumes:
      - /home/ssamadi/data/WordPress:/var/www/html
  wordpress:
      build: ./srcs/requirements/wordpress/.
      image: wordpress
      container_name: wordpress
      ports:
        - 9000:9000
      networks:
        - Inception
      volumes:
        - /home/ssamadi/data/WordPress:/var/www/html

networks:
  Inception:
        name: Inception
        

  
