version: "2.4"
services:
  nginx:
    build: ./srcs/requirements/nginx/.
    image: nginx
    ports:
      - 443:443
    container_name: nginx
    networks:
      - Inception
  wordpress:
      build: ./srcs/requirements/wordpress/.
      image: wordpress
      container_name: wordpress
      networks:
        - Inception

networks:
  Inception:
        name: Inception
        

  
